name: buon_appetito
description: An APP to order your  pizzas


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: 8.1.0
  flutter_bloc: 8.1.1
  equatable: 2.0.5
  get_it: 7.2.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
